
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Gradle Plugins
loom_version=1.10-SNAPSHOT
arch_plugin_version=3.4-SNAPSHOT
shadow_version=8.3.8

quiltflower_version=1.11.0

grgit_version=5.3.2
cursegradle_version=1.4.0
modrinth_version=2.8.7
github_api_version=1.327

# Mod Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
enabled_platforms=fabric,forge

# Project Properties
archives_base_name=builtin-servers
mod_version=2.1+1.21.11
maven_group=io.github.lucaargolo

architectury_version=17.0.6

# Fabric Properties
fabric_loader_version=0.18.02
fabric_api_version=0.128.2+1.21.11

# Forge Properties
forge_version=1.21.11-113
#Publishing
curseforge_id=00
modrinth_id=00


