name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant executable permissions to Gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to GitHub
        if: ${{ github.secrets.GH_API_KEY != '' }}
        run: ./gradlew github
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}
      - name: Publish to CurseForge
        if: ${{ github.secrets.CURSEFORGE_API_KEY != '' }}
        run: ./gradlew curseforge
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      - name: Publish to Modrinth
        if: ${{ github.secrets.MODRINTH_TOKEN != '' }}
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
